name: rikulo_eul
version: 0.5.0
description: >
  Rikulo EUL (Embeddable User-interface Language) is a markup language
  allowing developers to define user-interface in HTML 5 and XML.
authors:
- Tom Yeh <tomyeh@rikulo.org>
- Henri Chen <henrichen@rikulo.org>
homepage: http://rikulo.org
dependencies:
  unittest: any
  rikulo_commons: { git: git://github.com/rikulo/commons.git }
  rikulo: { git: git://github.com/rikulo/rikulo.git }
  rikulo_el: { git: git://github.com/rikulo/el.git }
